# Generated by Django 5.1.6 on 2025-06-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='land_images/'),
        ),
    ]
