# Generated by Django 5.1.6 on 2025-06-26 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_projectproposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('advance_given', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('organization_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Client.projectproposal')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('rate_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='Client.projectcommit')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('daily_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('days_worked', models.PositiveIntegerField()),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='Client.projectcommit')),
            ],
        ),
    ]
